/**
 * Graph types for Planner output
 *
 * These graphs represent the compiled structure of a game,
 * generated by the Planner Agent from a GameSpec.
 */

import type { Position } from './gamespec';

/**
 * Camera configuration for scene
 */
export interface CameraConfig {
  follow: string;
  bounds?: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
}

/**
 * Scene graph - describes scene hierarchy and camera
 */
export interface SceneGraph {
  scenes: SceneNode[];
  camera: CameraConfig;
  worldBounds: {
    width: number;
    height: number;
  };
}

/**
 * Scene node
 */
export interface SceneNode {
  id: string;
  type: 'main' | 'menu' | 'gameover' | 'level';
  entities: string[];
}

/**
 * Entity graph - describes entity relationships
 */
export interface EntityGraph {
  nodes: EntityNode[];
  edges: EntityEdge[];
}

/**
 * Entity node in the graph
 */
export interface EntityNode {
  id: string;
  type: string;
  parentId?: string;
  children: string[];
  position: Position;
}

/**
 * Edge between entities
 */
export interface EntityEdge {
  from: string;
  to: string;
  type: EntityRelationType;
}

export type EntityRelationType =
  | 'spawns'
  | 'follows'
  | 'collides'
  | 'triggers'
  | 'contains';

/**
 * Component graph - describes component bindings
 */
export interface ComponentGraph {
  entityComponents: Record<string, string[]>;
}

/**
 * System graph - describes system dependencies
 */
export interface SystemGraph {
  systems: SystemNode[];
  dependencies: SystemDependency[];
}

/**
 * System node
 */
export interface SystemNode {
  type: string;
  enabled: boolean;
  config?: Record<string, unknown>;
}

/**
 * System dependency
 */
export interface SystemDependency {
  system: string;
  requires: string[];
}

/**
 * Complete plan result from Planner
 */
export interface PlanResult {
  sceneGraph: SceneGraph;
  entityGraph: EntityGraph;
  componentGraph: ComponentGraph;
  systemGraph: SystemGraph;
  diagnostics: PlanDiagnostics;
}

/**
 * Planning diagnostics
 */
export interface PlanDiagnostics {
  warnings: string[];
  autoFixes: string[];
  inferredNodes: string[];
}
