/**
 * Code Generator
 *
 * Generates Phaser.js game code from execution graphs
 */

import type {
  SceneGraph,
  EntityGraph,
  ComponentGraph,
  SystemGraph,
  GameSpec,
  AdapterBinding,
  Entity,
} from '@loom/core';
import type {
  CodeGeneratorInput,
  CodeGeneratorOutput,
  CodeGeneratorOptions,
  GeneratedFile,
  GeneratorDiagnostics,
  TemplateContext,
  EntityTemplateData,
} from './types';

export class CodeGenerator {
  private diagnostics: GeneratorDiagnostics = {
    warnings: [],
    errors: [],
    generatedFiles: [],
    skippedFiles: [],
  };

  /**
   * Generate complete Phaser project from graphs
   */
  generate(input: CodeGeneratorInput, options: Partial<CodeGeneratorOptions> = {}): CodeGeneratorOutput {
    this.resetDiagnostics();

    const { gameSpec, sceneGraph, entityGraph, componentGraph, systemGraph } = input;

    const files: GeneratedFile[] = [];

    // Stage 1: Generate package.json
    files.push(this.generatePackageJson(gameSpec));

    // Stage 2: Generate index.html
    files.push(this.generateIndexHtml(gameSpec));

    // Stage 3: Generate game config
    files.push(this.generateConfig(gameSpec, systemGraph));

    // Stage 4: Generate main scene
    files.push(this.generateMainScene(gameSpec, sceneGraph, entityGraph, componentGraph));

    // Stage 5: Generate main entry point
    files.push(this.generateMain(gameSpec));

    // Stage 6: Generate TypeScript config
    files.push(this.generateTsConfig());

    // Stage 7: Generate vite config
    files.push(this.generateViteConfig());

    // Collect dependencies
    const dependencies: Record<string, string> = {
      phaser: '^3.70.0',
    };

    return {
      files,
      dependencies,
      entryPoint: 'index.html',
      diagnostics: this.diagnostics,
    };
  }

  /**
   * Generate package.json
   */
  private generatePackageJson(gameSpec: GameSpec): GeneratedFile {
    const packageJson = {
      name: `loom-game-${gameSpec.meta.title.toLowerCase().replace(/\s+/g, '-')}`,
      version: '1.0.0',
      description: gameSpec.meta.description || `Generated by Loom - ${gameSpec.meta.title}`,
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      dependencies: {
        phaser: '^3.70.0',
      },
      devDependencies: {
        vite: '^5.0.0',
        typescript: '^5.3.0',
      },
    };

    this.diagnostics.generatedFiles.push('package.json');

    return {
      path: 'package.json',
      content: JSON.stringify(packageJson, null, 2),
      type: 'package',
    };
  }

  /**
   * Generate index.html
   */
  private generateIndexHtml(gameSpec: GameSpec): GeneratedFile {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${gameSpec.meta.title}</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      background-color: #1a1a1a;
    }
    #game-container {
      box-shadow: 0 0 20px rgba(0,0,0,0.5);
    }
  </style>
</head>
<body>
  <div id="game-container"></div>
  <script type="module" src="/src/main.ts"></script>
</body>
</html>`;

    this.diagnostics.generatedFiles.push('index.html');

    return {
      path: 'index.html',
      content: html,
      type: 'html',
    };
  }

  /**
   * Generate game config
   */
  private generateConfig(gameSpec: GameSpec, systemGraph: SystemGraph): GeneratedFile {
    const gravity = gameSpec.settings.gravity || 980;
    const width = gameSpec.settings.worldBounds?.width || 800;
    const height = gameSpec.settings.worldBounds?.height || 600;
    const bgColor = gameSpec.settings.backgroundColor || '#000000';

    const config = `import Phaser from 'phaser';
import { MainScene } from './scenes/MainScene';

export const GameConfig: Phaser.Types.Core.GameConfig = {
  type: Phaser.AUTO,
  parent: 'game-container',
  width: ${width},
  height: ${height},
  backgroundColor: '${bgColor}',
  physics: {
    default: 'arcade',
    arcade: {
      gravity: { x: 0, y: ${gravity} },
      debug: false
    }
  },
  scene: [MainScene]
};
`;

    this.diagnostics.generatedFiles.push('src/config.ts');

    return {
      path: 'src/config.ts',
      content: config,
      type: 'config',
    };
  }

  /**
   * Generate main scene
   */
  private generateMainScene(
    gameSpec: GameSpec,
    sceneGraph: SceneGraph,
    entityGraph: EntityGraph,
    componentGraph: ComponentGraph
  ): GeneratedFile {
    // Build entity declarations
    const entityDeclarations = this.generateEntityDeclarations(gameSpec.entities);

    // Build preload code
    const preloadCode = this.generatePreloadCode(gameSpec);

    // Build create code
    const createCode = this.generateCreateCode(gameSpec, entityGraph, componentGraph);

    // Build update code
    const updateCode = this.generateUpdateCode(gameSpec, componentGraph);

    const scene = `import Phaser from 'phaser';

export class MainScene extends Phaser.Scene {
${entityDeclarations}

  constructor() {
    super({ key: 'MainScene' });
  }

  preload() {
${preloadCode}
  }

  create() {
${createCode}
  }

  update(time: number, delta: number) {
${updateCode}
  }
}
`;

    this.diagnostics.generatedFiles.push('src/scenes/MainScene.ts');

    return {
      path: 'src/scenes/MainScene.ts',
      content: scene,
      type: 'scene',
    };
  }

  /**
   * Generate entity declarations
   */
  private generateEntityDeclarations(entities: Entity[]): string {
    const declarations: string[] = [];

    for (const entity of entities) {
      const varName = this.getEntityVarName(entity.id);
      const type = entity.type === 'player' ? 'Phaser.Physics.Arcade.Sprite' : 'Phaser.Physics.Arcade.Sprite';

      declarations.push(`  private ${varName}!: ${type};`);
    }

    return declarations.join('\n');
  }

  /**
   * Generate preload code
   */
  private generatePreloadCode(gameSpec: GameSpec): string {
    const lines: string[] = [];

    // Load sprites
    for (const entity of gameSpec.entities) {
      if (entity.sprite) {
        const spriteKey = entity.sprite;
        const spritePath = `assets/sprites/${spriteKey}.png`;
        lines.push(`    this.load.image('${spriteKey}', '${spritePath}');`);
      }
    }

    if (lines.length === 0) {
      lines.push('    // No assets to preload');
    }

    return lines.join('\n');
  }

  /**
   * Generate create code
   */
  private generateCreateCode(
    gameSpec: GameSpec,
    entityGraph: EntityGraph,
    componentGraph: ComponentGraph
  ): string {
    const lines: string[] = [];
    lines.push('    // Create entities');

    // Create entities
    for (const entity of gameSpec.entities) {
      const varName = this.getEntityVarName(entity.id);
      const x = entity.position?.x || 0;
      const y = entity.position?.y || 0;
      const sprite = entity.sprite || 'placeholder';

      lines.push(`    this.${varName} = this.physics.add.sprite(${x}, ${y}, '${sprite}');`);

      // Add physics properties
      if (entity.physics?.collidable) {
        lines.push(`    this.${varName}.setCollideWorldBounds(true);`);
      }
    }

    lines.push('');
    lines.push('    // Setup collisions');

    // Setup collisions (simplified)
    const players = gameSpec.entities.filter(e => e.type === 'player');
    const enemies = gameSpec.entities.filter(e => e.type === 'enemy');

    if (players.length > 0 && enemies.length > 0) {
      lines.push('    // Player-Enemy collision');
      lines.push('    this.physics.add.collider(');
      lines.push(`      this.${this.getEntityVarName(players[0].id)},`);
      lines.push('      this.enemies,');
      lines.push('      this.handlePlayerEnemyCollision,');
      lines.push('      undefined,');
      lines.push('      this');
      lines.push('    );');
    }

    lines.push('');
    lines.push('    // Setup camera');
    if (players.length > 0) {
      lines.push(`    this.cameras.main.startFollow(this.${this.getEntityVarName(players[0].id)});`);
    }

    return lines.join('\n');
  }

  /**
   * Generate update code
   */
  private generateUpdateCode(gameSpec: GameSpec, componentGraph: ComponentGraph): string {
    const lines: string[] = [];
    lines.push('    // Update logic');

    // Add basic input handling for player
    const players = gameSpec.entities.filter(e => e.type === 'player');
    if (players.length > 0) {
      const playerVar = this.getEntityVarName(players[0].id);

      // Check if player has jump component
      const playerComponents = componentGraph.entityComponents[players[0].id] || [];
      if (playerComponents.includes('jump')) {
        lines.push('');
        lines.push('    // Player jump');
        lines.push(`    const cursors = this.input.keyboard?.createCursorKeys();`);
        lines.push(`    const spaceKey = this.input.keyboard?.addKey('SPACE');`);
        lines.push('');
        lines.push(`    if (spaceKey?.isDown && this.${playerVar}.body?.touching.down) {`);
        lines.push(`      this.${playerVar}.setVelocityY(-320);`);
        lines.push('    }');
      }
    }

    return lines.join('\n');
  }

  /**
   * Generate main entry point
   */
  private generateMain(gameSpec: GameSpec): GeneratedFile {
    const main = `import Phaser from 'phaser';
import { GameConfig } from './config';

window.addEventListener('load', () => {
  new Phaser.Game(GameConfig);
});
`;

    this.diagnostics.generatedFiles.push('src/main.ts');

    return {
      path: 'src/main.ts',
      content: main,
      type: 'config',
    };
  }

  /**
   * Generate TypeScript config
   */
  private generateTsConfig(): GeneratedFile {
    const tsconfig = {
      compilerOptions: {
        target: 'ES2020',
        useDefineForClassFields: true,
        module: 'ESNext',
        lib: ['ES2020', 'DOM', 'DOM.Iterable'],
        skipLibCheck: true,
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true,
      },
      include: ['src'],
    };

    this.diagnostics.generatedFiles.push('tsconfig.json');

    return {
      path: 'tsconfig.json',
      content: JSON.stringify(tsconfig, null, 2),
      type: 'config',
    };
  }

  /**
   * Generate Vite config
   */
  private generateViteConfig(): GeneratedFile {
    const viteConfig = `import { defineConfig } from 'vite';

export default defineConfig({
  base: './',
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    sourcemap: true,
  },
  server: {
    port: 3000,
    open: true,
  },
});
`;

    this.diagnostics.generatedFiles.push('vite.config.ts');

    return {
      path: 'vite.config.ts',
      content: viteConfig,
      type: 'config',
    };
  }

  /**
   * Get entity variable name
   */
  private getEntityVarName(entityId: string): string {
    return entityId.replace(/-/g, '_');
  }

  /**
   * Reset diagnostics
   */
  private resetDiagnostics(): void {
    this.diagnostics = {
      warnings: [],
      errors: [],
      generatedFiles: [],
      skippedFiles: [],
    };
  }
}

/**
 * Create default code generator instance
 */
export const codeGenerator = new CodeGenerator();
